2025-10-19 10:21:41 - stitch - ERROR - This is an error message
2025-10-19 10:21:41 - stitch - CRITICAL - This is a critical message
2025-10-19 10:21:41 - stitch - ERROR - This is an exception with traceback
Traceback (most recent call last):
  File "/workspace/stitch_logger.py", line 140, in <module>
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
